### ISSUE TITLE
Class constructor with argument Map<?,?> and HashMap<?,?>

### ISSUE THREAD

**Issue by asifbakht** [davidmarquis/fluent-interface-proxy#13]
Issue with pojo constructor where constructor is taking Map<String,Object> as argument
and passing Object is HashMap<String,Object> throws error that constructor not found.

```
public class Payload {
    private final Map<String, Object> data;
    public Payload(final Map<String,Object> data){
      this.data = data;
    }
}

static PayloadBuilder aMessage() {
		return ReflectionBuilder.implementationFor(PayloadBuilder.class).create();
	}

public static Payload default() {
               Map<String,Object> data = new HashMap<String,Object>();
               data.put("a","b");
		return aMessage() //
				.of(data) //
				.build();
	}
```
java.lang.IllegalArgumentException: No constructor found on class [Payload] that matches signature (class java.util.HashMap])
	at com.fluentinterface.proxy.impl.BestMatchingConstructor.findMatchingConstructor(BestMatchingConstructor.java:56)
	at com.fluentinterface.proxy.impl.BestMatchingConstructor.instantiate(BestMatchingConstructor.java:30)
	at com.fluentinterface.proxy.BuilderProxy.createInstanceFromProperties(BuilderProxy.java:74)
	at com.fluentinterface.proxy.BuilderProxy.invoke(BuilderProxy.java:57)
	at com.sun.proxy.$Proxy166.build(Unknown Source)

**Comment by davidmarquis** [comment]
What version of the library are you using? 

I tried a similar case and it worked with the latest version of the library.

**Comment by asifbakht** [comment]
Hello
I am using latest version and my constructor is taking argument as
Map<String, Object> and when I use builder and push Map as HashMap it shows
exception that constructor signature is not matching

Because constructor is checking absolute class
java.util.Map.class
While passing argument is java.util.Hashmap.class

Also I checked with Map Builder<String, Object> and have one issue.
I want to put different object ( int, string, list, list of HashMap or
HashMap) in Object and many more compiler will raise issue. Because the
first element adding in map or mappingOf will be considered the the
argument object

So if I code MapBuilder<String, Object> x = mappingOf(key, 1).and(key,
"2").and(key, list of map)

Compiler will raise issue

**Comment by davidmarquis** [comment]
The stack trace you sent earlier references the exception as being raised on line 56 of `BestMatchingConstructor`:

```
java.lang.IllegalArgumentException: No constructor found on class [Payload] that matches signature (class java.util.HashMap])
at com.fluentinterface.proxy.impl.BestMatchingConstructor.findMatchingConstructor(BestMatchingConstructor.java:56)
```

... which is [not even a valid line](https://github.com/davidmarquis/fluent-interface-proxy/blob/26954a629884d0c3b8f79c8c2c08a5ecf94aa6e4/src/main/java/com/fluentinterface/proxy/internal/BestMatchingConstructor.java#L56) in latest version (`2.2.0`)

You should probably consider using `2.2.0` and see if it improves your case.

I added a test to the test suite in order to cover you exact case:
https://github.com/davidmarquis/fluent-interface-proxy/commit/8e72fff6cd1f496c76a01773269caead994fea65

If upgrading to 2.2.0 does not fix your issue, please let me know how the above test differs from your usage and I'll try it up.

**Comment by asifbakht** [comment]
Sorry just checked now it was 2.1.0 
And yes it is working in 2.2.0 
Thanks

**Comment by davidmarquis** [comment]
Alright, enjoy!
